In [4]:
%matplotlib inline
import scipy
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns
sns.set(color_codes=True)

Two coins: A, B
- A: p(H) = 0.8
- B: p(H) = 0.45

5 experiments of 10 flips, but we don't know which coin was used:
- HTTTHHTHTH (B)
- HHHHTHHHHH (A)
- HTHHHHHTHH (A)
- HTHTTTHHTT (B)
- THHHTHHHTH (A)

In [5]:
X = np.array([[0, 1, 1, 1, 0, 0, 1, 0, 1, 0], 
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0], 
[0, 1, 0, 0, 0, 0, 0, 1, 0, 0], 
[0, 1, 0, 1, 1, 1, 0, 0, 1, 1], 
[1, 0, 0, 0, 1, 0, 0, 0, 1, 0]])

In [32]:
#parameters to learn:
pA = 0.6
pB = 0.5

In [38]:
r = np.zeros((X.shape[0], 2))

In [41]:
for t in range(5):
    # E step
    for i in range(X.shape[0]):
        #for k in range(2):
        # calc probability of coin flips i using coin k
        num_tails = np.sum(X[i,:])
        num_heads = X.shape[1] - num_tails
        r[i,0] = scipy.special.binom(X.shape[1], num_heads) * (pA**num_heads) * ((1-pA)**(num_tails))
        r[i,1] = scipy.special.binom(X.shape[1], num_heads) * (pB**num_heads) * ((1-pB)**(num_tails))
    # renormalize
    #print(r)
    z = np.sum(r, axis=1)
    #print(z)
    r[:,0] = r[:, 0] / z
    r[:,1] = r[:, 1] / z
    print(r)
    print(np.sum(r, axis=0))
    coinA = 
    # M step
    pA = pA

[[ 0.44914893  0.55085107]
 [ 0.80498552  0.19501448]
 [ 0.73346716  0.26653284]
 [ 0.35215613  0.64784387]
 [ 0.64721512  0.35278488]]
[ 2.98697285  2.01302715]
[[ 0.44914893  0.55085107]
 [ 0.80498552  0.19501448]
 [ 0.73346716  0.26653284]
 [ 0.35215613  0.64784387]
 [ 0.64721512  0.35278488]]
[ 2.98697285  2.01302715]
[[ 0.44914893  0.55085107]
 [ 0.80498552  0.19501448]
 [ 0.73346716  0.26653284]
 [ 0.35215613  0.64784387]
 [ 0.64721512  0.35278488]]
[ 2.98697285  2.01302715]
[[ 0.44914893  0.55085107]
 [ 0.80498552  0.19501448]
 [ 0.73346716  0.26653284]
 [ 0.35215613  0.64784387]
 [ 0.64721512  0.35278488]]
[ 2.98697285  2.01302715]
[[ 0.44914893  0.55085107]
 [ 0.80498552  0.19501448]
 [ 0.73346716  0.26653284]
 [ 0.35215613  0.64784387]
 [ 0.64721512  0.35278488]]
[ 2.98697285  2.01302715]


In [46]:
.45*5 + .8*9 + 0.73*8 + .35*4 + .65*7 

21.24

In [44]:
(.45*5+(1-.45)*5) + (.8*9 + (1-.8)*1) + (0.73*8 + (1-.73)*2) + (.35*4 + (1-.35)*6) + (.65*7 + (1-.65)*3)

29.68

In [47]:
21.24/29.68

0.715633423180593